


#define littleGift_VERSION_MAJOR 0
#define littleGift_VERSION_MINOR 3

/* #undef CPPHTTPLIB_ZLIB_SUPPORT */

#define CPPHTTPLIB_THREAD_POOL_COUNT 64
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#define LOG_FILE_NAME "littleGift.log"

